name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci  # Clean install instead of npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Ensure Playwright is installed
        run: npx playwright --version  # Debugging step

      - name: Verify test files exist
        run: ls -R tests  # Check if test files exist

      - name: Run Playwright tests
        run: npx playwright test
